language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- nvm install 7
- npm install -g npm && node -v && npm -v
- npm install -g @angular/cli && ng -v
install:
- npm install
script:
- ng test --code-coverage --single-run=true
- npm run build:package
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: diegoraguiar@gmail.com
  skip_cleanup: true
  api_key:
    secure: gF3GMhcWD94/HgbOj+zjaM9pb0hQ8mwhkBl1XWrBfWy02f7wqXm53xx+8Tg4IhwR/Usr8s7o8Q8t4xYhU/QijJeDwmRS4Xlk25q30e70GaPgODFmcyN7wnOq2jhWHzeRWcm1ENxbcbn+6q8U45JO5N7JJyqYJUCcVlA/Qzs+jFwlkbWOIMB9t2ZT7qVS4KwyjGDdiOxH2xL7782iWfUioJPSI5rINPMMn0jW9Pk2HbI4engcbnE3TJ+1hOjj4OAzDfV1oGs9TjLWeahxjcxb1dBoY6EQlmauVhlXqxFy1y2vpJ6Njo6aAEgD2ocSIT1srvjI2eKC7GZ2dULZktSzqQtuahn8uyy3B/7KLBooNvxRI/e5K1ai8/XuGoQZS7RyI+pKH8SS5n9wI/dLPUZE34a1xSHqxwiNQCRmtmTyfjjPQ6Ejp5+NOR8faFgxYadcO2kwbU1EEf3nVf6+mfm2QRf+yPyUM3lzhnX6zsArUTFntDcFYxjQennn92ef/oN2LnXpXYV1nvoeKWi0joOjC1n3zff3Y8a09+Vi+iIsRwDdbFWy6O0YvCdnpqKM0JGyxGeVJkryhxK0XR+cDRnP30+rI4GlQD0YudNC9rjid6urtK09aWdUOq6rXGR5anPj50UBvVO9bHKUeWcWvE0qgd5e7pugbn+PY50z74C6REM=
  on:
    tags: true
    branch: master
    repo: diegoraguiar/ngx-brazilian-helpers
notifications:
  email: false
