language: node_js
sudo: false

cache:
  directories:
  - node_modules

before_install:
  - nvm install 7
  - npm install -g npm && node -v && npm -v
  - npm install -g @angular/cli && ng -v

install:
  - npm install

script:  
  - npm test --code-coverage --single-run=true
  - npm run build:package