language: node_js
node_js:
- '0.12'
sudo: false
env:
  - PACKAGE_VERION=$(cat package.json | grep version | head -1 | awk -F= \"{ print $2 }\" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
cache:
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: "diegoraguiar-github"
    token:
      secure: "Yd3HvhAbS5+HF92bGeUcS3TAWVhQ1Qq2iQ/tNXKjbcDdFKvYDltDkcNA+M63230zhwMp1kG7ZPKVStszgVUhWiaMdCGWASEJYXwi9R5lVGItdOhMrmHVBG9Pc07Bt+N3egZ2F2by6MUKpJqIm2TvU8Z6kXD8FOEbsuZ9ASXrYHK0/sh6eIAm9NKIJWYUn3Qp/Ocrv2THvK27C1uB6WSbxQxYUqHQozpKHYCx+Gqhyjp4VPIrBkM9Sqf7I9oG/mKYuwL670jiz+Y/AyR1mbOT6Ar6SSvoSpt0fEkzOjG2l0uLq+I84ZNwnBNy0/066sfcin7iFc8MUAQoMO1EuyqLElFzS83a5xkCSgIN0fxoAgpzZMr5GFqNSM1acLP2En44REzM+3qxE1tsxwRsq4GhZG6IFPvXK4ueVlvXseW/x+K1n08fjPMwt/cppHlunSC65FTT2xoPSjns7/0B0XdpKmIfUaYADvdgxAurbctbd69j25RmJoMa0bwMot10AAFu6hhdXMQ0us/W1CK2agyz8ZmItCyoNAZJQ6eEYtHtkR1RUWHIH6pucMOzCcM6S/SGUWpoCtrCZM0fGlFuGfCJChpa31WUC+Tvrddej6b0dpP1dzrCnS5CRyFiEjpDhrxxFERjV6VxMofRJuAmeqgvapZepRO2uZrPBH97arrZcr4="
    branches:
      - master
before_install:
- nvm install 7
- npm install -g npm && node -v && npm -v
- npm install -g @angular/cli && ng -v
install:
- npm install
script:
- ng test --code-coverage --single-run=true
- npm run build:package
- sonar-scanner -Dsonar.projectVersion=$PACKAGE_VERION
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: diegoraguiar@gmail.com
  skip_cleanup: true
  api_key:
    secure: gF3GMhcWD94/HgbOj+zjaM9pb0hQ8mwhkBl1XWrBfWy02f7wqXm53xx+8Tg4IhwR/Usr8s7o8Q8t4xYhU/QijJeDwmRS4Xlk25q30e70GaPgODFmcyN7wnOq2jhWHzeRWcm1ENxbcbn+6q8U45JO5N7JJyqYJUCcVlA/Qzs+jFwlkbWOIMB9t2ZT7qVS4KwyjGDdiOxH2xL7782iWfUioJPSI5rINPMMn0jW9Pk2HbI4engcbnE3TJ+1hOjj4OAzDfV1oGs9TjLWeahxjcxb1dBoY6EQlmauVhlXqxFy1y2vpJ6Njo6aAEgD2ocSIT1srvjI2eKC7GZ2dULZktSzqQtuahn8uyy3B/7KLBooNvxRI/e5K1ai8/XuGoQZS7RyI+pKH8SS5n9wI/dLPUZE34a1xSHqxwiNQCRmtmTyfjjPQ6Ejp5+NOR8faFgxYadcO2kwbU1EEf3nVf6+mfm2QRf+yPyUM3lzhnX6zsArUTFntDcFYxjQennn92ef/oN2LnXpXYV1nvoeKWi0joOjC1n3zff3Y8a09+Vi+iIsRwDdbFWy6O0YvCdnpqKM0JGyxGeVJkryhxK0XR+cDRnP30+rI4GlQD0YudNC9rjid6urtK09aWdUOq6rXGR5anPj50UBvVO9bHKUeWcWvE0qgd5e7pugbn+PY50z74C6REM=
  on:
    tags: true
    branch: master
    repo: diegoraguiar/ngx-brazilian-helpers
notifications:
  email: false
